### ISSUE TITLE
Using RxAdapter with androidx libraries

### ISSUE THREAD

**Issue by DamienAtBuddy** [marcbaldwin/RxAdapter#3]
Will this be library be updated to extend the androidx libraries.

Damien

**Comment by marcbaldwin** [comment]
Sorry I didn't see this earlier! It has been updated to use AndroidX libs. However it's also been updated to use RxJava2. If you want to keep using RxJava1 with the AndroidX libs use commit `c3ade1a2c0d56f45a9f3c6dcc26ffd4f72a9d839`.
